[package]
name = "data_fetcher"
version = "0.1.0"
authors = ["Ilya <ilya.ryabchuk@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.10", features = ["blocking", "json"] }